services:
    nginx:
        image: nginx:1.19.0
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - wp_data:/usr/share/nginx/html
        depends_on:
            - wordpress

    wordpress:
        image: wordpress:5.4.2-php7.2-apache
        volumes:
            - wp_data:/var/www/html
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: example
            WORDPRESS_DB_NAME: wordpress
        deploy:
            replicas: 4

    locust:
        image: grubykarol/locust
        environment:
            ATTACKED_HOST: http://nginx
            LOCUST_USERS: 10
            LOCUST_SPAWN_RATE: 10
        ports:
            - 8089:8089
        volumes:
            - ./locust:/locust
        depends_on:
            - wordpress

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: wordpress
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    wp_data:
    mysql_data:
